package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_android_tools_deploy.jar",
    srcs = ["android_tools/all_android_tools_deploy.jar"],
)

filegroup(
    name = "desugar_jdk_libs.jar",
    srcs = ["android_tools/desugar_jdk_libs.jar"],
)

filegroup(
    name = "ImportDepsChecker_deploy.jar",
    srcs = ["android_tools/ImportDepsChecker_deploy.jar"],
)
